### ISSUE TITLE
Wrong musl target?

### ISSUE THREAD

**Issue by senden9** [timClicks/microservice-checksum#3]
The list of [supported platforms](https://forge.rust-lang.org/platform-support.html) does not list a `x86-unknown-linux-musl`. Did you mean `x86_64-unknown-linux-musl`?
https://github.com/timClicks/microservice-checksum/blob/9c48f4409d2b03b03b74ceda8217daf5c6558a8d/README.md#L103-L125

**Comment by timClicks** [comment]
Thanks for this! I've fixed that up :) in 3a0cc6b
